### ISSUE TITLE
Error Handler

### ISSUE THREAD

**Issue by MPlatypus** [hypergonial/hikari-miru#44]
### Summary

A way to handle errors in Miru, for example if a button goes unpressed, or a button is not handled for example.

### Why is this needed?

Its not overly needed, but could be extremely useful for finding issues in code, and debugging.

### Ideal implementation

To be decided.

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by hypergonial** [comment]
Does [this](https://hikari-miru.readthedocs.io/en/latest/guides/error_handling.html) not cover your usecase?

P.S. Sorry for taking this long to comment on this.

**Comment by MPlatypus** [comment]
I will have to look into it and see, sorry for the even worse response times. I will have a look into it once

**Comment by hypergonial** [comment]
Closing as stale.
